### ISSUE TITLE
IPython crashes each time I use the command line and give the command x = input() and apply a value for x

### ISSUE THREAD

**Issue by markos4code** [ipython/ipython#10494]
Dear all,

Each time I am in the command line of IPython and I try to perform the
following simple task, my iPython crashes:

lets name a simple variable as name and define it as follows:

>>>name = input()

so far so good.

then the command like asks me to import a value, lets say markos

>>>markos

as soon as I press enter to execute the command my iPython crashes at this
point of computation.

Note that this issue never occurs with simple python 27 or python 36
editions.

Could you please tell me why this happens and what workarounds are there
available?

The issue is consistent to all my IPython installations (pc, laptop).

Thank you ever so much for your assistance

**Comment by Carreau** [comment]
You'll need to provide more information like a traceback.

**Comment by markos4code** [comment]
Thank you for your immediate reply. Pleae find attached an icon to help
identify the problem. It's as simple as that. Just start a programme in
iPython by giving the command name = input()
and then place any value and iPython will just crash.

Thanks again for everything. I am using Greek Windows and I tried to
translate a few things. Please let me know if there's anything else you
would like me to translate in English.

Kind Regards
Markos Vougiouklis

2017-04-30 20:09 GMT+03:00 Matthias Bussonnier <notifications@github.com>:

**Comment by takluyver** [comment]
Unfortunately your attachment didn't come through. What version of IPython are you using? This sounds similar to #10484, which was solved by updating IPython.

**Comment by markos4code** [comment]
I am reattaching the icon for more info on the problem. I am using iPython 5.1.0 with the latest Anaconda distribution (4.3.1) for Python 3.6 on any Windows. It will just crash in any Windows. 
![problem [](icon](https://cloud.githubusercontent.com/assets/22731151/25625026/fba8321c-2f63-11e7-8ed1-5e2e6bc03c1d.png))

**Comment by Carreau** [comment]
Hi there, unfortunately GitHub does not allow attachment via email. You'll
have to upload manually by responding via the GitHub UI or host any
attachments in a separate website.

**Comment by Carreau** [comment]
Sorry mail client sent my reply with a delay. I still can't see the
attachment though.

**Comment by takluyver** [comment]
I do see the screenshot now, and I think it's similar to #10484. Can you try updating IPython (`conda update ipython`)? We've released 5.3 and 6.0.

**Comment by markos4code** [comment]
Thanks a lot Thomas. I' m on it now. I will let you know as soon as l
update. It's true l have made mo updates of my initial installation.
Regards
Markos Vougiouklis

Στις 3 Μαΐ 2017 12:57 ΜΜ, ο χρήστης "Thomas Kluyver" <
notifications@github.com> έγραψε:

**Comment by takluyver** [comment]
Closing this assuming it was fixed by updates somewhere along the line. Let us know if similar issues occur with an up to date version.
