### ISSUE TITLE
Weird character after first import

### ISSUE THREAD

**Issue by albireox** [ipython/ipython#11336]
I'm running python 7.0.1 Everything seems to work fine but after the first import I consistently get a weird symbol (see attached screenshot). When I press enter again the symbol goes away and doesn't reappear. I'm using fish shell on an iterm2 terminal on mac.

![screenshot 2018-09-27 at 13 51 00](https://user-images.githubusercontent.com/568775/46174104-fb146e00-c25c-11e8-9c46-2c99b7e578ad.png)

[Update]

Upgrade prompt_toolkit to 2.0.6 should fix the issue.

**Comment by Carreau** [comment]
Hum I've seen this one but with `^[[43;1R`, but I assumed it was due to me being on master of my terminal emulator. Not sure where this come from

**Comment by davidbrochart** [comment]
I've seen similar things in latest https://github.com/jonathanslenders/pymux (not released, uses prompt-toolkit 2). Maybe @jonathanslenders has some idea?

**Comment by matthew-brett** [comment]
I get the same:

```
$ ipython
Python 3.6.5 (default, Mar 30 2018, 06:41:53) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import os                                                                                             

^[[19;1RIn [2]:
```

If I then try to tab complete:

```
In [2]: os.p                                                                                                  
os.pardir         os.pathconf       os.pathsep        os.popen          os.putenv         
os.path           os.pathconf_names os.pipe           os.pread          os.pwrite         
^[[19;1RIn [2]: os.p
```

This makes tab completion almost unusable.

**Comment by jonathanslenders** [comment]
Is it possible that this was fixed by the following commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/e226d640177aa1d2cf293e4de382f171586173a2 ?
It's merged in prompt_toolkit master, but I'm about to release a new prompt_toolkit 2.0 which includes it.

**Comment by jonathanslenders** [comment]
No, I'm pretty sure this isn't IPython. I'll try to reproduce with iterm2

**Comment by matthew-brett** [comment]
I'm sure I'm not understanding the complexities here, but just for information, this does occur with IPython 7.0 and 7.1, and doesn't occur with 6.0 or 6.5, testing in the same virtualenv.

**Comment by Carreau** [comment]
Can you all post which terminal you've seen it in? 
I'm able to reproduce on iTerm2 – 3.2.1beta6  – osx; alacritty v0.2.0-35-ga53cabf osx, but not on bare macos terminal.app  (sierra 10.12.6) 

Could it be mismatch between advertized features  of terminal and what they actually can do ? 

It also not reproducible (to me) with `ipython --colors=nocolor`

**Comment by matthew-brett** [comment]
Just bare Terminal.app on High Sierra 10.13.6 .  `nocolor` doesn't fix it for me.

**Comment by Carreau** [comment]
> It also not reproducible (to me) with `ipython --colors=nocolor`

Scratch that, it seem to be random, but indeed, nocolor did not fix it.

**Comment by Carreau** [comment]
Can you guys try by removing [this `patch_stdout`](https://github.com/ipython/ipython/blob/194d1d7fe2fcc8547205bd7f54fcf63bee9df4e3/IPython/terminal/interactiveshell.py#L380) context manager ? 

If I remove it, it _seem_ fine to ne, and if I extra flush stdout I get the issue twice ..

**Comment by albireox** [comment]
Removing the context manager seems to fix it for me.

This happens to me in either the macOS Terminal.app and in iTerm2. However, the character appeared quite consistently in iTerm2 3.2.1beta. This morning I upgraded to 3.2.2beta1 and now the character seems to appear and immediately disappear, replaced by the normal iPython prompt. But at least in one case the character has been persistent, I'm not sure what was the difference.

**Comment by matthew-brett** [comment]
Yup, fixes it for me too.   The effect was always consistent for me.

**Comment by Carreau** [comment]
@jonathanslenders could it be that patch stdout had a race condition and that stdout/err are restored and start being written to before the flush have happened ? 

The `raw` parameter of patch_stdout seem to go nowhere also in the ptk code.

**Comment by Carreau** [comment]
So there is reason to have this, or otherwise printing in background threads would mess-up the rendering, but it looks (to me), that is is a race condition between flushing captured stderr/out and restoring to their initial value.

**Comment by nadesai** [comment]
I'm also getting this (macOS 10.11.6, iTerm 3.2.0beta5) very frequently, though not 100% of the time.

```
Python 3.7.0 (default, Jun 29 2018, 20:13:53)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sqlalchemy

^[[43;1RIn [2]:
```

**Comment by matthew-brett** [comment]
Yeah, this one is really killing me.  I'd downgrade, but that breaks Jupyter notebooks.   For me, tab completion is more or less completely broken, because these characters appear very frequently.

**Comment by matthew-brett** [comment]
No change running current master of `prompt_toolkit` (version 2.0.5).

**Comment by jonathanslenders** [comment]
I can reproduce it.

iTerm2 build 3.2.3 (I think the latest), IPython 7.0.1, Python 3.6.1.

**Comment by davidbrochart** [comment]
I had the bug with Python 3.6.3 on Ubuntu, and it disappeared with Python 3.7, although I can see some glitches (like the characters are printed and then quickly removed).

**Comment by jonathanslenders** [comment]
I have a fix here: https://github.com/jonathanslenders/python-prompt-toolkit/commit/09de545476be985b95ae2690ef8393efdd65b7e5

Actually what you see in this commit are two individual fixes that would both solve the issue (for what I could reproduce).

- For some reason, an empty string is captured and written to stdout, right before accepting the first input. This triggered the patch_stdout code. Actually, there was no need to go through the effort of erasing the prompt, and drawing it again, just for printing an empty string. (I still have to check why this is actually happening.) 

- The real fix is to wait for CPR responses before rendering the captured content. CPR works asynchronously. We ask for the cursor position by writing something to stdout, and we receive the response from the terminal on stdin. There is always a little delay. But it's important to keep the terminal in RAW mode and read this input until this response arrives. We didn't do that, and it rendered the terminal's own response with the cursor position.

The timing should have been slightly different between terminals, but I guess this should do it.

Could you all try with the latest prompt_toolkit commit? If it works, I'll push a new release.

**Comment by davidbrochart** [comment]
That fixes the bug on my side. Thanks @jonathanslenders !

**Comment by matthew-brett** [comment]
Yes, many thanks, latest master fixes it for me too.

**Comment by andreip** [comment]
That patch fixes some `[[39;1R` chars I was having too. Thanks!

**Comment by albireox** [comment]
No, this doesn't seem to fix it for me. Instead I get a different character

```
AlbireoProˇalbireo: Downloads » ipython                 (3.7.0 2.7.15)

In [1]: from can.interfaces.slcan import slcanBus

^[[21;1RIn [2]:
```

**Comment by Carreau** [comment]
> Could you all try with the latest prompt_toolkit commit? If it works, I'll push a new release.

works for me. You also change the handling of colors AFAICT, we were unwillingly relying on ansi mapping to ansi code in some places in IPython, I'll fix that as well. Thanks !

**Comment by jonathanslenders** [comment]
@Carreau: I just pushed prompt_toolkit 2.0.6.
Does IPython expect that certain RRGGBB sequences map to certain ANSI colors, even in 256color mode?

**Comment by jonathanslenders** [comment]
By the way @Carreau, one one feature of prompt_toolkit now is the ability to increase/decrease the brightness of the colors. This makes it easy to adjust to terminals with light or dark background. I've added this to the menu of ptpython for testing (interactively) and it works pretty well.

**Comment by Carreau** [comment]
> expect

I wouldn't say "expect" but the themes seem to have a mix of `#ansixxx` and `#00ff00` that looked good together, and with 2.0.6 are a bit stronger in their differences.

<img width="529" alt="screen shot 2018-10-12 at 10 03 56" src="https://user-images.githubusercontent.com/335567/46883195-1f984a80-ce06-11e8-8657-bf08cc54ab39.png">

I think we just need more consistencies as to whether we use `#ansi` or `#hex`.

I'll look at the brightness options at some point. I just have started a new position a few weeks ago and have a bit less time on developing IPython/jupyter  itself.

**Comment by Carreau** [comment]
closing as fixed upstream
