### ISSUE TITLE
Auto Completion Error?

### ISSUE THREAD

**Issue by rbeucher** [ipython/ipython#12828]
Hi,

I have the following toy code. I am trying to understand why autocomplete does not work when I override the
`__getattr__` method in the Test Class. I was expecting to see "class1" and "class2" as completion options...

Any idea?

```python
import logging


class MyClass(object):
    
    def __init__(self, A=None, B=None):
        self.A = A
        self.B = B


class Test(object):
    
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)
    
    def __init__(self):
        logging.info("init")
        self._dir = {"class1":{"A":1, "B":2}, "class2":{"A":2, "B":4}}
        self._keys = list(self._dir.keys())
        
    def __getattr__(self, name):
        logging.info(f"__getattr__ called: {name}")
        return MyClass(**self._dir[name])
    
    def __dir__(self):
        logging.info("__dir__ called")
        return self._keys

foo.class1
foo.class2


```

cheers,
R

**Comment by Carreau** [comment]
You likely need to look into what jedi is doing, the most likely reason is that __dir__ and __getattr__ may trigger side effects, and thus jedi does not execute them ?

**Comment by chrisjsewell** [comment]
Heya, I also encountered this issue, and the fix was to include `"__dir__"` in the retured list of `__dir__`, or more completely `dir(super())`:

```python
class MyClass:
   def __init__(self):
      self._fields = {'a': 1, 'b': 2, 'c': 3}
   def __getattr__(self, key):
       return self[key]
   def __dir__(self):
       return list(self._fields) + dir(super())
```

more weirdly, I also wanted to add a `__getitem__`, but found it only worked if I handled calls for `__wrapped__`:

```python
class MyClass:
   def __init__(self):
      self._fields = {'a': 1, 'b': 2, 'c': 3}
    def __getitem__(self, key):
        try:
            return self._fields[key]
        except KeyError:
            if key == '__wrapped__':
                return None
            raise
   def __getattr__(self, key):
       return self[key]
   def __dir__(self):
       return list(self._fields) + dir(super())
```

(this is with python 3.8, ipython 7.26.0, and jedi 0.18.0)

**Comment by chrisjsewell** [comment]
actually ignore being an idiot lol: I should have been raising an `AttributeError`:

```python
    def __getattr__(self, key):
        try:
            return self._fields[key]
        except KeyError:
            raise AttributeError(key)
```

**Comment by MrMino** [comment]
Looks like this has been fixed already:

![image](https://user-images.githubusercontent.com/6691643/160292188-4b1b1392-7fd0-4629-aa0c-d274c2fac078.png)

If anyone thinks it's not - ping here and we'll reopen.

**Comment by krassowski** [comment]
I believe that I can reproduce this issue on 8.6.0/main. This happens regardless of greedy completer setting. My Jedi version is 0.18.1.

![Screenshot from 2022-11-19 23-44-00](https://user-images.githubusercontent.com/5832902/202875938-49abcba8-95d7-4e52-a94a-c028fd6afb6f.png)

I will reopen while I investigate.  @MrMino do you happen to remember in which environment it was working well for you so we could compare versions?

**Comment by krassowski** [comment]
Ok, I found the cause. It only works if jedi is disabled because `__dir__` only gets called by `python_matches` → `attr_matches` code path and `python_matches` is only ever included if `use_jedi=False`. So this is still an issue.

![Screenshot from 2022-11-20 00-02-33](https://user-images.githubusercontent.com/5832902/202876342-f36cd8a4-7f91-4ae9-ad76-b6f3957903f5.png)

**Comment by krassowski** [comment]
The root issue is that `__wrapped__` attribute of `t` gets accessed by Jedi. This leads to `KeyError` (as `self._dir` in the example does not have such a key) which can be reproduced with:

```python
In [2]: t.__wrapped__
KeyError                                  Traceback (most recent call last)
Cell In [2], line 1
----> 1 t.__wrapped__

Cell In [1], line 24, in Test.__getattr__(self, name)
     22 logging.info(f"__getattr__ called: {name}")
---> 23 return MyClass(**self._dir[name])

KeyError: '__wrapped__'
```

To see that it is coming from jedi we can add `logging.info(''.join(traceback.format_stack()))` in the `__getattr__` implementation:

<details>

```python
import logging
import traceback

class MyClass(object):
    
    def __init__(self, A=None, B=None):
        self.A = A
        self.B = B


class Test(object):
    
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)
    
    def __init__(self):
        logging.info("init")
        self._dir = {"class1":{"A":1, "B":2}, "class2":{"A":2, "B":4}}
        self._keys = list(self._dir.keys())
        
    def __getattr__(self, name):
        logging.info(f"__getattr__ called: {name}")
        logging.info(''.join(traceback.format_stack()))
        return MyClass(**self._dir[name])
    
    def __dir__(self):
        logging.info("__dir__ called")
        return self._keys
        
t = Test()
```

</details>

Which will show that `__wrapped__` gets referenced from within `inspect.unwrap` from `jedi`:

```python
  File "~/site-packages/jedi/inference/compiled/mixed.py", line 272, in _create
    result = _find_syntax_node_name(inference_state, python_object)
  File "~/site-packages/jedi/inference/compiled/mixed.py", line 188, in _find_syntax_node_name
    python_object = _get_object_to_check(python_object)
  File "~/site-packages/jedi/inference/compiled/mixed.py", line 165, in _get_object_to_check
    python_object = inspect.unwrap(python_object)
  File "~/lib/python3.9/inspect.py", line 521, in unwrap
    while _is_wrapper(func):
  File "~/lib/python3.9/inspect.py", line 512, in _is_wrapper
    return hasattr(f, '__wrapped__')
  File "<ipython-input-3-fbbdb243f3bf>", line 23, in __getattr__
    logging.info(''.join(traceback.format_stack()))
```

<details>

```python
  File "~/ipython/IPython/terminal/ptutils.py", line 122, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "~/ipython/IPython/terminal/ptutils.py", line 138, in _get_completions
    for c in completions:
  File "~/ipython/IPython/core/completer.py", line 769, in _deduplicate_completions
    completions = list(completions)
  File "~/ipython/IPython/core/completer.py", line 2471, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "~/ipython/IPython/core/completer.py", line 2521, in _completions
    results = self._complete(
  File "~/ipython/IPython/core/completer.py", line 2809, in _complete
    result = cast(matcher, MatcherAPIv2)(context)
  File "~/ipython/IPython/core/completer.py", line 1887, in _jedi_matcher
    matches = self._jedi_matches(
  File "~/ipython/IPython/core/completer.py", line 1968, in _jedi_matches
    return filter(completion_filter, interpreter.complete(column=cursor_column, line=cursor_line + 1))
  File "~/site-packages/jedi/api/helpers.py", line 487, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "~/site-packages/jedi/api/__init__.py", line 214, in complete
    return completion.complete()
  File "~/site-packages/jedi/api/completion.py", line 170, in complete
    cached_name, completion_names = self._complete_python(leaf)
  File "~/site-packages/jedi/api/completion.py", line 284, in _complete_python
    cached_name, n = self._complete_trailer(dot.get_previous_leaf())
  File "~/site-packages/jedi/api/completion.py", line 385, in _complete_trailer
    values = infer_call_of_leaf(inferred_context, previous_leaf)
  File "~/site-packages/jedi/inference/helpers.py", line 79, in infer_call_of_leaf
    return context.infer_node(leaf)
  File "~/site-packages/jedi/inference/context.py", line 224, in infer_node
    return infer_node(self, node)
  File "~/site-packages/jedi/inference/syntax_tree.py", line 156, in infer_node
    return _infer_node_if_inferred(context, element)
  File "~/site-packages/jedi/inference/syntax_tree.py", line 169, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "~/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "~/site-packages/jedi/inference/syntax_tree.py", line 174, in _infer_node_cached
    return _infer_node(context, element)
  File "~/site-packages/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "~/site-packages/jedi/inference/syntax_tree.py", line 82, in wrapper
    return func(context, *args, **kwargs)
  File "~/site-packages/jedi/inference/syntax_tree.py", line 184, in _infer_node
    return infer_atom(context, element)
  File "~/site-packages/jedi/inference/syntax_tree.py", line 304, in infer_atom
    return context.py__getattribute__(atom, position=position)
  File "~/site-packages/jedi/inference/context.py", line 77, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "~/site-packages/jedi/inference/base_value.py", line 430, in from_sets
    for set_ in sets:
  File "~/site-packages/jedi/inference/context.py", line 77, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "~/site-packages/jedi/cache.py", line 112, in wrapper
    result = method(self, *args, **kwargs)
  File "~/site-packages/jedi/inference/compiled/mixed.py", line 137, in infer
    return _create(self._inference_state, compiled_value, module_context)
  File "~/site-packages/jedi/inference/cache.py", line 44, in wrapper
    rv = function(obj, *args, **kwargs)
  File "~/site-packages/jedi/inference/compiled/mixed.py", line 272, in _create
    result = _find_syntax_node_name(inference_state, python_object)
  File "~/site-packages/jedi/inference/compiled/mixed.py", line 188, in _find_syntax_node_name
    python_object = _get_object_to_check(python_object)
  File "~/site-packages/jedi/inference/compiled/mixed.py", line 165, in _get_object_to_check
    python_object = inspect.unwrap(python_object)
  File "~/lib/python3.9/inspect.py", line 521, in unwrap
    while _is_wrapper(func):
  File "~/lib/python3.9/inspect.py", line 512, in _is_wrapper
    return hasattr(f, '__wrapped__')
  File "<ipython-input-3-fbbdb243f3bf>", line 23, in __getattr__
    logging.info(''.join(traceback.format_stack()))
```

</details>

The user-side solution as correctly noted in https://github.com/ipython/ipython/issues/12828#issuecomment-902991224 is to raise `AttributeError` rather than `KeyError`.
