### ISSUE TITLE
Unable to contact kernel in Firefox after updating to ipython 3.0

### ISSUE THREAD

**Issue by wikiped** [ipython/ipython#7943]
After updating to ipython 3.0 (from 2.4.1) notebooks opened in Firefox v.37 cannot connect to kernel anymore (all Firefox addons  and windows firewall are disabled). This happens both on python 2.8 and 3.4 environments. 

Here is info from `Help | About` notebook menu:

```
About IPython Notebook
Server Information:
You are using IPython notebook.
The version of the notebook server is 3.0.0-f75fda4 and is running on:
Python 3.4.2 |Continuum Analytics, Inc.| (default, Jan  9 2015, 10:32:40) [MSC v.1600 64 bit (AMD64)]
Current Kernel Information:
unable to contact kernel
```

Terminal shows kernel running ok:

```
[I 13:11:57.791 NotebookApp] Creating new notebook in
[I 13:11:59.209 NotebookApp] Kernel started: 6f7fb8a8-0179-4581-b300-ad44706a46da
```

Removing ipython 3.0 and installing back 2.4.1 gets notebooks to work fine.
Are there any additional steps required to get ipython 3.0 working with Firefox as it does with 2.4.1 (besides installing `jsonschema` package that was not required in 2.4.1)?

By the way opening the same notebook (ipython 3.0) in Internet Explorer works fine. 

Thanks.

**Comment by takluyver** [comment]
It's probably JavaScript caching issues. Hit ctrl-f5 a few times and see if
it's resolved.

**Comment by jorisvandenbossche** [comment]
I experience the same issue.

Windows 7, Firefox 35, but also in explorer

**Comment by jorisvandenbossche** [comment]
Renewing the page sometimes solves it, but it is very flaky. 

- Sometimes I get a completely grey page (even not the top toolbal)
- Sometimes I get the toolbar, but no content shown (and if you do the "About", you get  the "unable to contact kernel"
- Sometimes, after some multiple times renewing, I finally get at the notebook with content and kernel connected. But even after shutting down the notebook and restarting it, I have to go again through this cycle of the three bullet points.

Some other things:
- I cleared the cache of firefox. This didn't help
- is it possible this has to do something with your profile? Should your profile be updated for ipython 3?
- Possibly to do with some extensions that are not updated to ipython 3? I have in my default profile some nbextensions (toc, copy/pasting multiple cells, slideview, etc). And when I end up in the second bullet point above, I still see the contours of these extra buttons in the toolbar (but no icons). When I end up in the third bullet point above (working notebook), these buttons are gone.

**Comment by jorisvandenbossche** [comment]
It indeed seems to be related to my extensions, as with a clean profile, I don't have these issues.

**Comment by takluyver** [comment]
Aha, that sounds promising. Are there any errors in your browser JS console when the extensions do load?

**Comment by wikiped** [comment]
`Ctrl+F5` did not help.
I have tried disabling all extensions by launching Firefox in Safe Mode - did not help.

But after creating New profile the problem is gone... 
It's weird.

If I will figure out the extension which is causing the problem I will report back.

**Comment by takluyver** [comment]
> I have tried disabling all extensions by launching Firefox in Safe Mode - did not help.

I think @jorisvandenbossche was talking about *IPython* extensions - starting Firefox in safe mode won't affect those.

**Comment by wikiped** [comment]
Well in my case it seems the cause is linked to _Firefox_ profile as problem is gone in freshly created profile in firefox.

**Comment by takluyver** [comment]
I'd guess that's a JS caching issue still. Things can get cached quite a lot, even Ctrl-F5 doesn't always work.

**Comment by ebellm** [comment]
I'm also having this problem in Firefox 36 on OS X 10.8.5.  

Cache-clearing reloads don't fix the problem, nor does creating a new ipython profile.  The notebook works fine in Chrome on the same machine, though.

Looking at the JS console, there are a handful of warnings and one SecurityError:

```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
"Default extension for cell metadata editing loaded." default.js:48:8
"Raw Cell Format toolbar preset loaded." rawcell.js:82:4
"Slideshow extension for metadata editing loaded." slideshow.js:43:8
Use of Mutation Events is deprecated. Use MutationObserver instead. jquery.min.js:5:0
SecurityError: The operation is insecure. manager.js:112:0
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:5:0
"Can't execute, kernel is not connected." codecell.js:391:12
```

**Comment by takluyver** [comment]
What about creating a new *Firefox* profile?

**Comment by jorisvandenbossche** [comment]
Examples of what I get in the webconsole when the notebook does not load correctly:
```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
TypeError: IPython.load_extensions is not a function custom.js:63:0
"Table of Contents extension loaded" custom.js:54:4
<link type="text/css" rel="stylesheet" href="/nbextensions/toc.css?v=20150303203557"> toc.js:147:4
"copy_paste extension loaded" custom.js:60:4
Gebruik van getPreventDefault() wordt niet meer ondersteund. Gebruik in plaats daarvan defaultPrevented. jquery.min.js:5:0
Error: Load timeout for modules: codemirror/lib/codemirror,jqueryui
http://requirejs.org/docs/errors.html#timeout require.js:166:16
```



```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
TypeError: IPython.load_extensions is not a function custom.js:63:0
"Table of Contents extension loaded" custom.js:54:4
<link type="text/css" rel="stylesheet" href="/nbextensions/toc.css?v=20150303203557"> toc.js:147:4
"copy_paste extension loaded" custom.js:60:4
Gebruik van Mutation Events wordt niet meer ondersteund. Gebruik in plaats daarvan MutationObserver. jquery.min.js:5:0
"Default extension for cell metadata editing loaded." default.js:48:8
"Raw Cell Format toolbar preset loaded." rawcell.js:82:4
"Slideshow extension for metadata editing loaded." slideshow.js:43:8
Gebruik van getPreventDefault() wordt niet meer ondersteund. Gebruik in plaats daarvan defaultPrevented. jquery.min.js:5:0
TypeError: action is undefined toolbar.js:127:24
"Live slideshow extension correctly loaded" main.js:324:0
```

**Comment by ebellm** [comment]
@takluyver : Okay, yes: if I create an new Firefox profile, the notebook executes as expected.  Notably, the error ``SecurityError: The operation is insecure. manager.js:112:0`` is no longer present in the js console.

**Comment by ebellm** [comment]
@takluyver : Okay, yes: if I create an new Firefox profile, the notebook executes as expected.  Notably, the error ``SecurityError: The operation is insecure. manager.js:112:0`` is no longer present in the js console.

**Comment by minrk** [comment]
@ebellm can you try with IPython master? I think the SecurityError is fixed (or rather, isn't fatal) by #7908.

**Comment by takluyver** [comment]
@jorisvandenbossche OK, thanks. I'm still inclined to think caching issues of some kind, because I can't think what else would cause that.

@ebellm aha, is it possible that you had cookies disabled in your original profile? [That line](https://github.com/ipython/ipython/blob/rel-3.0.0/IPython/html/static/widgets/js/manager.js#L112) accesses localStorage, which apparently can raise a SecurityError if cookies are disabled.

**Comment by jorisvandenbossche** [comment]
@takluyver But if it is a caching issue, isn't it strange that it is resolved by using a clean ipython profile? (also, it keeps repeating with the same notebook, also after it once succeeded)

**Comment by takluyver** [comment]
The IPython profile won't affect it - the caching is done in the browser. You could try starting with `--port 9473` (pick any number you haven't used the notebook on before), that should start with a blank cache.

Non-deterministic things suggest that the load order is involved - JS pieces are loaded asynchronously, so they will finish in different orders.

**Comment by jorisvandenbossche** [comment]
Using a random port does not solve it, still the same issue.

When I get a full grey page (even no toolbar), I see this error:

```
Error: Load timeout for modules: codemirror/lib/codemirror,jqueryui     require.js:166:16
http://requirejs.org/docs/errors.html#timeout 
```

**Comment by ebellm** [comment]
@takluyver: Ah, yes, disabled cookies was the problem.  If I enable cookies then my original Firefox profile also works correctly.  

Thanks for your help!

**Comment by takluyver** [comment]
@ebellm OK, glad we got it worked out. As @minrk said, that issue should be fixed (i.e. it should work with cookies disabled) for the next bugfix release.

@jorisvandenbossche OK, so it is some sort of race condition. Is there any reason it would be unusually slow? Do you have firebug? The URL in that error mentions that firebug might hide some relevant error details.

**Comment by wikiped** [comment]
Thanks @ebellm - added `localhost` to cookies whitelist and the problem is gone.

@takluyver shall we close the issue then?

**Comment by jorisvandenbossche** [comment]
@takluyver Just first to check: it is maybe expected that my notebook extensions for ipython 2 don't work anymore and can possibly break ipython 3, and I should update them anyway? Or is this not expected, and should I dig further?

In firebug, I get the same error message. Can I see more there in some way?

**Comment by takluyver** [comment]
It's expected (or not surprising, at least), that some extensions from v2 don't work in v3, but it's a bit unfortunate that they break the notebook itself as well. Can you work out if it's a specific extension causing it?

**Comment by jorisvandenbossche** [comment]
I did some tests, commenting out all extensions, and it seems it is (at least) the copy-paste extension that triggers an error preventing the notebook to connect/load.

Sometimes I get a `Error: Load timeout for modules: codemirror/lib/codemirror,jqueryui` error, but most of the time I get a `TypeError: action is undefined` error.

Do I need to dif further?

**Comment by takluyver** [comment]
No, I think that's sufficient for now. If someone wants to update that extension, that might be good. We do mean to get round to integrating the functionality into IPython, but I don't know if it will make it for 4.0.

**Comment by jorisvandenbossche** [comment]
@takluyver I am still experiencing some issues (not with the error that caused the kernel not to connect, that was due to one of the extensions, but with the not loading of the notebook page).

I took following precautions:

- made a new clean ipython profile
- made a new folder without any content
- started `ipython notebook` with this profile, and on a port that I never use
- cleared the cache of my firefox

Still, in one of two/three cases that I try to open a notebook, I get a full gray page without any content. When I refresh, eventually, I always get the notebook (actually, this is not only for notebooks, but the same applies to the dashboard navigation).  
In the cases with a gray page, get the following error in the webconsole:

    Error: Load timeout for modules: codemirror/lib/codemirror,jqueryui
    http://requirejs.org/docs/errors.html#timeout                                             require.js:166:16

**Comment by takluyver** [comment]
I think I've seen that on occasion when I do a hard-refresh and it's trying to reload everything at the same time. It looks like the default timeout is ([7 seconds](http://requirejs.org/docs/api.html#config-waitSeconds)). Is there any reason it might be slower than expected? Maybe we just need to increase the timeout. Or maybe the plan to concatenate modules together will help.

**Comment by minrk** [comment]
The plan to concat javascript will definitely help. In the meantime, we probably should relax the timeout while we have a huge number of js requests to do. I've hit it a number of times trying to visit our hosted instances on horrible conference wifi this week.

**Comment by histed** [comment]
> Maybe we just need to increase the timeout. Or maybe the plan to concatenate modules together will help.

Increasing the timeout doesn't seem to work.  Could it be a problem with codemirror?
With IPython 3.2.0, I have in custom.js
```
requirejs.config({waitSeconds: 20});
require(["base/js/events"], function (events) {
    $([IPython.events]).on("app_initialized.NotebookApp", function () {
        require(["components/codemirror/keymap/emacs"], function () {
            console.log('test')
        });
    });
});
```

JS console on Chrome shows the error:

```
require.js?v=640929dac3c23a448d2eebc37bc32062:166 
Uncaught Error: Load timeout for modules: components/codemirror/lib/codemirror
http://requirejs.org/docs/errors.html#timeout
```

And the require.js site link says a possibility for timeout error is:
> There was a script error in one of the listed modules. If there is no script error in the browser's error console, and if you are using Firebug, try loading the page in another browser like Chrome or Safari.

**Comment by takluyver** [comment]
Closing to clean up an old issue. I think the comments may have included several issues with similar symptoms. As we're nearly three years on, if you see similar problems with current versions, please open new issues on jupyter/notebook.
